### ISSUE TITLE
Running `cake build` causes an error

### ISSUE THREAD

**Issue by brennanMKE** [luckymarmot/Paw-JavaScriptjQueryCodeGenerator#2]
Details below.

```
> cake build
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn coffee ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
  at child_process.js:1137:20
  at process._tickCallback (node.js:355:11)

> node -v
v0.12.0
```

**Comment by kwent** [comment]
Could you try `sudo npm install -g coffee-script` ?

**Comment by mittsh** [comment]
Right. We should add this to the dependencies, or make the `Cakefile` use the locally installed version of CoffeeScript.

**Comment by mittsh** [comment]
@brennanMKE anyways, as @kwent said, running `sudo npm install -g coffee-script` will fix your issue.

**Comment by brennanMKE** [comment]
It seems to be working now. Thanks.

**Comment by mittsh** [comment]
:+1:

**Comment by JonathanMontane** [comment]
fixed

**Comment by jayeshd2493** [comment]
i performed the steps but still getting same error please help.
thanks in advance.
